name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'  # Run weekly on Mondays

env:
  NODE_VERSION: "18"

jobs:
  project-health:
    name: Project Health Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for dependency vulnerabilities
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: TypeScript health check
      run: npm run type-check || echo "TypeScript issues detected"
      continue-on-error: true

    - name: ESLint health check
      run: npm run lint || echo "Lint issues detected"
      continue-on-error: true

    - name: Check project structure
      run: |
        echo "Checking essential files..."
        test -f package.json && echo "✅ package.json" || echo "❌ package.json missing"
        test -f Anchor.toml && echo "✅ Anchor.toml" || echo "❌ Anchor.toml missing"
        test -f Cargo.toml && echo "✅ Cargo.toml" || echo "❌ Cargo.toml missing"
        test -d programs/aura-lend/src && echo "✅ Program source" || echo "❌ Program source missing"
        test -d sdk/src && echo "✅ SDK source" || echo "❌ SDK source missing"
        test -d tests && echo "✅ Tests directory" || echo "❌ Tests directory missing"

    - name: Generate health report
      run: |
        echo "## Project Health Report" > health-report.md
        echo "Generated on: $(date)" >> health-report.md
        echo "" >> health-report.md
        echo "### Dependencies Status" >> health-report.md
        npm list --depth=0 >> health-report.md 2>&1 || echo "Some dependency issues detected" >> health-report.md
        echo "" >> health-report.md
        echo "### Project Structure" >> health-report.md
        find . -type f -name "*.rs" -o -name "*.ts" -o -name "*.js" | head -20 >> health-report.md

    - name: Upload health report
      uses: actions/upload-artifact@v3
      with:
        name: health-report
        path: health-report.md